services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTypo3ContentPlanner\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.ximatypo3contentplanner_toolbarcache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'ximatypo3contentplanner_toolbarcache' ]

  Xima\XimaTypo3ContentPlanner\Backend\ToolbarItems\UpdateItem:
    arguments:
      $cache: '@cache.ximatypo3contentplanner_toolbarcache'

  Xima\XimaTypo3ContentPlanner\EventListener\DrawBackendHeaderListener:
      tags:
          -   name: event.listener
              identifier: 'xima-typo3-content-planner/backend/modify-page-module-content'

  Xima\XimaTypo3ContentPlanner\EventListener\AfterPageTreeItemsPreparedListener:
      tags:
          -   name: event.listener
              identifier: 'xima-typo3-content-planner/backend/modify-page-tree-items'

  Xima\XimaTypo3ContentPlanner\EventListener\ModifyButtonBarEventListener:
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-planner/backend/modify-button-bar'

  dashboard.widget.ContentStatus-danger:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              status: 'danger'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-danger'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.danger.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.danger.description'
              iconIdentifier: 'flag-red'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-info:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              status: 'info'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-info'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.info.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.info.description'
              iconIdentifier: 'flag-blue'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-warning:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              status: 'warning'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-warning'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.warning.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.warning.description'
              iconIdentifier: 'flag-yellow'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-success:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              status: 'success'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-success'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.success.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.success.description'
              iconIdentifier: 'flag-green'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-current:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              currentUserAssignee: true
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-current'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.current.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.current.description'
              iconIdentifier: 'flag-gray'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-comments:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentCommentWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentCommentDataProvider'
          $options:
              refreshAvailable: true
              currentUserAssignee: true
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-comment'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.comment.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.comment.description'
              iconIdentifier: 'content-message'
              height: 'medium'
              width: 'medium'

  dashboard.widget.ContentStatus-overview:
      class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\StatusOverviewDataProvider'
          $options:
              icon: 'content-widget-chart-pie'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-overview'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.overview.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.overview.description'
              iconIdentifier: 'content-widget-chart-pie'
              height: 'medium'

  dashboard.widget.ContentStatus-note:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentNoteWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentNoteDataProvider'
      tags:
          -   name: dashboard.widget
              identifier: 'contentStatus-note'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.note.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.note.description'
              iconIdentifier: 'content-thumbtack'
              height: 'medium'

  dashboard.widget.ContentStatus-update:
    class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentUpdateWidget'
    arguments:
      $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentUpdateDataProvider'
    tags:
      -   name: dashboard.widget
          identifier: 'contentStatus-update'
          groupNames: 'contentPlanner'
          title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.update.title'
          description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentStatus.update.description'
          iconIdentifier: 'content-thumbtack'
          height: 'medium'
